
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port